### ISSUE TITLE
Suppress stdout from runner

### ISSUE THREAD

**Issue by bj0** [wimglenn/advent-of-code-data#21]
Is it possible to suppress stdout when using the `aoc` runner?  The output from print statements tends to destroy the runner output.

**Comment by wimglenn** [comment]
You can do this directly in your entry-point.  For example, in [`advent-of-code-wim`](https://github.com/wimglenn/advent-of-code-wim) I redirect stdout to a `StringIO` instance: https://github.com/wimglenn/advent-of-code-wim/blob/925223bb1aab7fb7b905b20b78ed897203d82d2a/aoc_wim/__init__.py#L13-L18

There is also stdlib [`contextlib.redirect_stdout`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) that can be used.

Since other users might _not_ want prints captured, I'm not sure it's a good idea for `aocr` itself to suppress stdout too.  But I will consider to add a CLI option for it.

**Comment by bj0** [comment]
Ah I didn't think about redirecting it in the entry point function.  I was actually thinking about it being a CLI option, but I guess the entry point is an easy enough workaround.

**Comment by wimglenn** [comment]
@bj0  This is added in advent-of-code-data v1.1.0.  Thanks for the suggestion.
