### ISSUE TITLE
Read session in browser cookiestore

### ISSUE THREAD

**Issue by ewjoachim** [wimglenn/advent-of-code-data#27]
An extra dependency to [`browsercookie`](https://pypi.org/project/browsercookie/) could let users use aocd without having to export their session manually.

This is what I've been using before I discovered this package:
```python
import requests, browsercookie  # from the pypi packages of the same names

def get_input(day):
    return requests.get(
		f"https://adventofcode.com/2020/day/{day}/input",
		cookies=browsercookie.firefox()
	).text
```
Would you be interested in integrating this ?

**Comment by wimglenn** [comment]
AOCD actually has something similar with already in [`cookies.py`](https://github.com/wimglenn/advent-of-code-data/blob/master/aocd/cookies.py). It uses [browser-cookie3](https://github.com/borisbabic/browser_cookie3) instead, which is a more actively maintained fork of the same project you mentioned.

There are problems with completely automating the cookie jar though, so the script [`aocd-token`](https://github.com/wimglenn/advent-of-code-data/blob/ed7cd3ff807228d5e78abbde02276231182ce986/setup.py#L15) simply prints the token to stdout, it's still up to user to export that to environment variable or put into file (`~/.config/aocd/token`). Since this is a once-off task that only needs to be done once a year, I don't mind too much the manual step.

These are the issues I encountered:
1. How to handle users with multiple accounts? I validate my code against multiple inputs by using all auth modes (reddit, google, twitter, github) but the browser cookie jar can only store one at a time.
2. Having to guess whether user browses with Chrome or Firefox, or maybe they use some other browser entirely that the browsercookie code doesn't support.
3. On macOS it pops up an authentication dialog warning that Python is trying to access private storage files, and rightly so - the cookie storage does contain sensitive data. Maybe it's for best that the user must opts-in to accessing their own secrets, rather than having the code automatically scraping them?

**Comment by ewjoachim** [comment]
I missed the fact that there's already something in place.

And your points make a lot of sense.
