### ISSUE TITLE
Cache easter eggs

### ISSUE THREAD

**Issue by jdherg** [wimglenn/advent-of-code-data#67]
I think `easter_eggs` is the last `Puzzle` property that always triggers a request against the site -- it's probably worth caching it.

I don't think this is particularly urgent (and if you don't get a chance to get to it I'm happy to put a PR together :) )

Thanks for the super-handy library! It's been fun integrating it into my workflow this year.

**Comment by wimglenn** [comment]
The reason I hadn't bothered to cache it is that nothing in the [runner](https://github.com/wimglenn/advent-of-code-data/blob/master/aocd/runner.py) uses it, so it's not a property that gets accessed under normal usage.

I wouldn't be against caching these too, but it's also a little tricky because in some cases I think an easter egg is only present in the part B text.

**Comment by wimglenn** [comment]
These will be cached in the upcoming 2.0.0 release, under the mechanism described in my previous comment (html cache)
